services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        # volumes:
        #     - .:/app
        depends_on:
            - mysql

        environment:
          APP_ENV: prod

    mysql:
        image: mysql:8.4
        platform: linux/amd64
        healthcheck:
            test: '/usr/bin/mysql --execute "SHOW databases;"'
            timeout: 3s
            interval: 1s
            retries: 10
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        cap_add:
            - SYS_NICE # prevent "mbind: Operation not permitted" errors
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "8080:8080"
        # volumes:
        #     - .:/app
        depends_on:
            - php
